# Generated by Django 4.2.7 on 2024-01-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='id_proofs/')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
