# Generated by Django 4.2.7 on 2024-01-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remaining_time_ps4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='remaining_time_ps5',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
