# Generated by Django 4.2.7 on 2024-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_remaining_time_ps4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='remaining_time_ps4',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remaining_time_ps5',
            field=models.BigIntegerField(default=0),
        ),
    ]
