# Generated by Django 4.2.7 on 2024-02-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_remaining_time_ps4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='remaining_time_ps4',
            new_name='ps4_tokens',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='remaining_time_ps5',
            new_name='ps5_tokens',
        ),
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
