# Generated by Django 4.2.7 on 2024-02-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_remaining_time_ps4_customer_ps4_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
