# Generated by Django 4.2.7 on 2024-01-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('PS5', 'PS5'), ('PS4', 'PS4'), ('Pool', 'Pool'), ('Snooker', 'Snooker')], max_length=50, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('PS5', 'PS5'), ('PS4', 'PS4'), ('Pool', 'Pool'), ('Snooker', 'Snooker')], max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('number_of_players', models.IntegerField()),
                ('planned_duration', models.DurationField()),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('admin_duration', models.DurationField(blank=True, null=True)),
                ('paid_in_cash', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('paid_online', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
