# Generated by Django 4.2.7 on 2024-02-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_pricing_duration_minutes_pricing_price_per_frame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='duration_minutes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
