# Generated by Django 4.2.7 on 2024-02-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_pricing_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_per_frame',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
